export const cardPath = {
    hearts_A: "../../../assets/card/card_hearts_A.png",
    hearts_02: "../../../assets/card/card_hearts_02.png",
    hearts_03: "../../../assets/card/card_hearts_03.png",
    hearts_04: "../../../assets/card/card_hearts_04.png",
    hearts_05: "../../../assets/card/card_hearts_05.png",
    hearts_06: "../../../assets/card/card_hearts_06.png",
    hearts_07: "../../../assets/card/card_hearts_07.png",
    hearts_08: "../../../assets/card/card_hearts_08.png",
    hearts_09: "../../../assets/card/card_hearts_09.png",
    hearts_10: "../../../assets/card/card_hearts_10.png",
    hearts_J: "../../../assets/card/card_hearts_J.png",
    hearts_Q: "../../../assets/card/card_hearts_Q.png",
    hearts_K: "../../../assets/card/card_hearts_K.png",
    diamonds_A: "../../../assets/card/card_diamonds_A.png",
    diamonds_02: "../../../assets/card/card_diamonds_02.png",
    diamonds_03: "../../../assets/card/card_diamonds_03.png",
    diamonds_04: "../../../assets/card/card_diamonds_04.png",
    diamonds_05: "../../../assets/card/card_diamonds_05.png",
    diamonds_06: "../../../assets/card/card_diamonds_06.png",
    diamonds_07: "../../../assets/card/card_diamonds_07.png",
    diamonds_08: "../../../assets/card/card_diamonds_08.png",
    diamonds_09: "../../../assets/card/card_diamonds_09.png",
    diamonds_10: "../../../assets/card/card_diamonds_10.png",
    diamonds_J: "../../../assets/card/card_diamonds_J.png",
    diamonds_Q: "../../../assets/card/card_diamonds_Q.png",
    diamonds_K: "../../../assets/card/card_diamonds_K.png",
    clubs_A: "../../../assets/card/card_clubs_A.png",
    clubs_02: "../../../assets/card/card_clubs_02.png",
    clubs_03: "../../../assets/card/card_clubs_03.png",
    clubs_04: "../../../assets/card/card_clubs_04.png",
    clubs_05: "../../../assets/card/card_clubs_05.png",
    clubs_06: "../../../assets/card/card_clubs_06.png",
    clubs_07: "../../../assets/card/card_clubs_07.png",
    clubs_08: "../../../assets/card/card_clubs_08.png",
    clubs_09: "../../../assets/card/card_clubs_09.png",
    clubs_10: "../../../assets/card/card_clubs_10.png",
    clubs_J: "../../../assets/card/card_clubs_J.png",
    clubs_Q: "../../../assets/card/card_clubs_Q.png",
    clubs_K: "../../../assets/card/card_clubs_K.png",
    spades_A: "../../../assets/card/card_spades_A.png",
    spades_02: "../../../assets/card/card_spades_02.png",
    spades_03: "../../../assets/card/card_spades_03.png",
    spades_04: "../../../assets/card/card_spades_04.png",
    spades_05: "../../../assets/card/card_spades_05.png",
    spades_06: "../../../assets/card/card_spades_06.png",
    spades_07: "../../../assets/card/card_spades_07.png",
    spades_08: "../../../assets/card/card_spades_08.png",
    spades_09: "../../../assets/card/card_spades_09.png",
    spades_10: "../../../assets/card/card_spades_10.png",
    spades_J: "../../../assets/card/card_spades_J.png",
    spades_Q: "../../../assets/card/card_spades_Q.png",
    spades_K: "../../../assets/card/card_spades_K.png",
    back: "../../../assets/card/card_back.png",
}

// Path: ../../../public/../public/assets/card/





